// react/src/components/VictimList.jsx
import React from 'react';

import style from './VictimList.css';

const VictimList = ({ victims, deleteVictim }) => {
  return (
    <ul className="victim-list">
      {
        victims.map(victim =>
          <li className="victim" key={ victim.id }>
            { victim.name }
            <button className="victim-delete" onClick={ () => deleteVictim(victim.id) }>✕</button>
          </li>
        )
      }
    </ul>
  );
};

export default VictimList;

// angular/src/app/victim-list/victim-list.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import Victim from '../victim';

@Component({
  selector: 'app-victim-list',
  template: `
    <ul class="victim-list">
      <li class="victim" *ngFor="let victim of victims">
        {{ victim.name }}
        <button (click)="deleteVictim(victim)" class="victim-delete">✕</button>
      </li>
    </ul>
  `,
  styleUrls: ['./victim-list.component.css']
})
export class VictimListComponent {
  @Input() victims: Victim[];
  @Output() onDeleteVictim: EventEmitter<Victim> = new EventEmitter();

  deleteVictim(victim: Victim) {
    this.onDeleteVictim.emit(victim);
  }
}

<ul class="victim-list">
  <li class="victim">
    Test
    <button class="victim-delete">✕</button>
  </li>
</ul>
