// angular/src/app/add-victim/add-victim.component.ts
import { Component, EventEmitter, Output } from '@angular/core';

@Component({
  selector: 'app-add-victim',
  template: `
    <div class="add-container">
      <input
        class="victim-input"
        type="text"
        placeholder="The next victim..."
        autoFocus
        (keyup.enter)="addVictim(newVictim)"
        #newVictim />
      <button class="add-button" (click)="addVictim(newVictim)">+ Add</button>
    </div>
  `,
  styleUrls: ['./add-victim.component.css']
})
export class AddVictimComponent {
  @Output() onAddVictim: EventEmitter<string> = new EventEmitter();

  addVictim(newVictim: HTMLInputElement) {
    this.onAddVictim.emit(newVictim.value);
    newVictim.value = '';
  }

}

<div class="add-container">
  <input
    class="victim-input"
    type="text"
    placeholder="The next victim..."
    autoFocus />
  <button class="add-button">+ Add</button>
</div>

// react/src/components/AddVictim.jsx
import React from 'react';

import style from './AddVictim.css';

export default class AddVictim extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      victim: ''
    };

    this.handleUpdateVictim = this.handleUpdateVictim.bind(this);
    this.handleAddVictim = this.handleAddVictim.bind(this);
  }

  handleUpdateVictim(event) {
    this.setState({
      victim: event.target.value
    });
  }

  handleAddVictim(event) {
    if (event.type === 'click' || event.key === 'Enter') {
      this.props.addVictim(this.state.victim);
      this.setState({
        victim: ''
      });
    }
  }

  render() {
    return (
      <div className="add-container">
        <input
          className="victim-input"
          type="text"
          placeholder="The next victim..."
          value={ this.state.victim }
          onChange={ this.handleUpdateVictim }
          onKeyUp={ this.handleAddVictim }
          autoFocus />
        <button className="add-button" onClick={ this.handleAddVictim } >+ Add</button>
      </div>
    )
  }
}
